# This is a basic workflow to help you get started with Actions

name: prod

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-base-for-prod:
    # Call all jobs from base.yml
    uses: ./.github/workflows/base.yml
    secrets:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      COMMON_HELMCHART_NAME: ${{ secrets.COMMON_HELMCHART_NAME }}
      COMMON_HELMCHART_VERSION: ${{ secrets.COMMON_HELMCHART_VERSION_PROD }}
      APP_NAME_BASE: ${{ secrets.APP_NAME }}
    with:
      values-file: values.prod.yaml
      # TODO: After migrating prod environment we can use the same image name for prod and non-prod
      image-name: ui
      git-version-mode: '/overrideconfig mode=Mainline'